'use client'

import { useState, useEffect, useMemo, useRef, useCallback } from 'react'
import { useRouter } from 'next/navigation'
import dynamic from 'next/dynamic'
import Link from 'next/link'
import { Search, Map, List, Bike, Navigation, Loader2 } from 'lucide-react'
import { ScooterCard } from '@/components/ride/ScooterCard'
import { ExploreFilters } from '@/components/ride/ExploreFilters'
import { ImageMetricsOverlay } from '@/components/debug/ImageMetricsOverlay'
import { cn } from '@/lib/utils'
import { sortByRecommended, shuffleUnpinned } from '@/lib/ridescore'
import { trackEvent } from '@/lib/analytics'
import { createExploreFuse } from '@/lib/fuzzy-search'
import { getZoneForLocation, getNearestZone } from '@/lib/zones'
import { useProfile } from '@/hooks/useProfile'
import { useAdminPanelVisible } from '@/hooks/useAdminPanelVisible'
import { useGeolocation } from '@/hooks/useGeolocation'
import { toast } from 'sonner'
import type { Scooter, FilterState } from '@/types'

function haversineKm(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const R = 6371
  const dLat = (lat2 - lat1) * Math.PI / 180
  const dLng = (lng2 - lng1) * Math.PI / 180
  const a = Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * Math.sin(dLng / 2) ** 2
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))
}

interface ScreenshotPin {
  id: string
  lat: number
  lng: number
  price: string
}

// Valid: "300" or "300+" — digits only, optional single trailing +
const PRICE_RE = /^\d+\+?$/

const ScooterMap = dynamic(() => import('@/components/map/ScooterMap'), {
  ssr: false,
  loading: () => (
    <div className="rounded-[20px] bg-[#0a0c10] border border-white/5 flex items-center justify-center" style={{ height: '100%' }}>
      <div className="w-7 h-7 border-2 border-[#FF6B35] border-t-transparent rounded-full animate-spin" />
    </div>
  ),
})

const DEFAULT_FILTERS: FilterState = {
  priceMin: 150,
  priceMax: 2000,
  category: 'all',
  deliveryNow: false,
  helmetIncluded: false,
  location: 'all',
  sortBy: 'recommended',
  depositProtected: false,
  noPassport: false,
  requiredFeatures: [],
  requiredAccessories: [],
  depositTypeFilter: '',
}

type MobileView = 'list' | 'map'

export default function ExploreClient({
  initialScooters,
  initialSearch = '',
  initialShopId,
}: {
  initialScooters: Scooter[]
  initialSearch?: string
  initialShopId?: string
}) {
  const router = useRouter()
  const { isAdmin, loading: profileLoading } = useProfile()
  const [adminPanelVisible] = useAdminPanelVisible()
  const { location: userLocation, loading: geoLoading, error: geoError, request: requestLocation } = useGeolocation()

  useEffect(() => {
    if (!geoError) return
    const msgs: Record<typeof geoError, string> = {
      denied:      'Location access denied. Enable it in Settings.',
      unavailable: 'Location unavailable on this device.',
      timeout:     'Location request timed out.',
      unknown:     'Unable to get your location.',
    }
    toast.error(msgs[geoError])
  }, [geoError])

  // Calibration tool: only available when ?debugPins=1 AND the current user is an admin.
  // Both conditions must be true — URL param alone is not enough.
  const hasDebugParam = typeof window !== 'undefined' &&
    new URLSearchParams(window.location.search).get('debugPins') === '1'
  const debugMode = !profileLoading && hasDebugParam && isAdmin

  // ── Screenshot pins (admin only, localStorage-backed) ───────
  const [screenshotMode, setScreenshotMode]   = useState(false)
  const [screenshotPins, setScreenshotPins]   = useState<ScreenshotPin[]>([])
  const [pendingPin, setPendingPin]           = useState<{ lat: number; lng: number } | null>(null)
  const [priceInput, setPriceInput]           = useState('')
  const priceInputRef                         = useRef<HTMLInputElement>(null)

  // Dynamic price ceiling: highest scooter price rounded up to the nearest ฿500
  const maxPrice = Math.ceil(
    Math.max(2000, ...initialScooters.map(s => s.pricePerDay)) / 500
  ) * 500

  const [filters, setFilters] = useState<FilterState>({ ...DEFAULT_FILTERS, priceMax: maxPrice })

  // One random seed per page session — generated once on mount so the default
  // (unfiltered) Explore shuffle stays stable while browsing, but differs on
  // the next visit/refresh. Never regenerated by re-renders.
  const [randomSeed] = useState(() => Math.floor(Math.random() * 2147483646) + 1)

  // Admin: show/hide "Recommended" sort option — persisted in localStorage
  const [showRecommended, setShowRecommended] = useState(() => {
    if (typeof window === 'undefined') return true
    return localStorage.getItem('adminShowRecommended') !== 'false'
  })
  const toggleRecommended = (next: boolean) => {
    setShowRecommended(next)
    try { localStorage.setItem('adminShowRecommended', String(next)) } catch {}
  }

  const [search, setSearch]           = useState(initialSearch)
  const [debouncedSearch, setDebouncedSearch] = useState(initialSearch)
  const searchDebounceRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const [selectedId, setSelectedId]   = useState<string | null>(null) // shop ID
  const [hoveredId, setHoveredId]     = useState<string | null>(null) // shop ID
  const [showMap, setShowMap]         = useState(true)

  // Persist map visibility across sessions — read after hydration to avoid SSR mismatch
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    if (localStorage.getItem('rp_show_map') === 'false') setShowMap(false)
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  // Screenshot pins: load from localStorage on mount (admin only)
  useEffect(() => {
    if (!isAdmin) return
    try {
      const stored = localStorage.getItem('screenshotPins')
      if (stored) setScreenshotPins(JSON.parse(stored))
    } catch {}
  }, [isAdmin]) // eslint-disable-line react-hooks/exhaustive-deps

  // Screenshot pins: persist to localStorage whenever they change
  useEffect(() => {
    if (!isAdmin) return
    try { localStorage.setItem('screenshotPins', JSON.stringify(screenshotPins)) } catch {}
  }, [screenshotPins, isAdmin])

  // Fuse instance — rebuilt only when the scooter list changes
  const fuse = useMemo(() => createExploreFuse(initialScooters), [initialScooters])

  // Debounce search → debouncedSearch so Fuse runs at most once per 200ms
  useEffect(() => {
    if (searchDebounceRef.current) clearTimeout(searchDebounceRef.current)
    searchDebounceRef.current = setTimeout(
      () => setDebouncedSearch(search.trim()),
      200,
    )
    return () => { if (searchDebounceRef.current) clearTimeout(searchDebounceRef.current) }
  }, [search])

  // Fuse result IDs — null means no search active (pass all through)
  const fuseMatchIds = useMemo((): Set<string> | null => {
    if (!debouncedSearch) return null
    return new Set(fuse.search(debouncedSearch).map(r => r.item.id))
  }, [fuse, debouncedSearch])

  const toggleMap = useCallback(() => {
    setShowMap(prev => {
      const next = !prev
      try { localStorage.setItem('rp_show_map', String(next)) } catch {}
      return next
    })
  }, [])
  const [mobileView, setMobileView]   = useState<MobileView>('list')
  const [mapBounds, setMapBounds]     = useState<{ sw: [number, number]; ne: [number, number] } | null>(null)
  const [shopIdFilter, setShopIdFilter] = useState<string | null>(initialShopId ?? null)

  useEffect(() => {
    if (initialShopId) {
      setShopIdFilter(initialShopId)
      setMobileView('list')
    }
  }, [initialShopId])

  const handleZoneClick = useCallback((key: string | null) => {
    setFilters(prev => ({ ...prev, location: key ?? 'all' }))
    if (key) setMobileView('list')
  }, [])

  const cardRefs   = useRef<Record<string, HTMLDivElement | null>>({})
  const filteredRef = useRef<Scooter[]>([])
  // Debounce timer for hover — prevents cascade re-renders on fast mouse movement
  const hoverTimer = useRef<ReturnType<typeof setTimeout> | null>(null)
  // Track which scooter pages have been prefetched to avoid duplicate prefetches
  const prefetched = useRef<Set<string>>(new Set())

  const setCardRef = useCallback((id: string) => (el: HTMLDivElement | null) => {
    cardRefs.current[id] = el
  }, [])

  // Receive shop ID from map, scroll to first scooter card of that shop
  const handleSelectFromMap = useCallback((shopId: string | null) => {
    setSelectedId(shopId)
    if (shopId) {
      const firstScooter = filteredRef.current.find(s => s.shopId === shopId)
      if (firstScooter && cardRefs.current[firstScooter.id]) {
        cardRefs.current[firstScooter.id]?.scrollIntoView({ behavior: 'smooth', block: 'nearest' })
      }
    }
  }, [])

  // ── Debounced hover — avoids thrashing ScooterMap marker updates ─
  // 40ms debounce: imperceptible to the user, cuts re-renders by ~10× on fast mousing.
  const handleHoverEnter = useCallback((shopId: string) => {
    if (hoverTimer.current) clearTimeout(hoverTimer.current)
    hoverTimer.current = setTimeout(() => setHoveredId(shopId), 40)
  }, [])

  const handleHoverLeave = useCallback(() => {
    if (hoverTimer.current) clearTimeout(hoverTimer.current)
    hoverTimer.current = setTimeout(() => setHoveredId(null), 40)
  }, [])

  const handleNearMe = useCallback(() => {
    requestLocation()
    setFilters(prev => ({ ...prev, sortBy: 'distance' }))
  }, [requestLocation])

  // ── Screenshot pin handlers ──────────────────────────────────
  const handleScreenshotPinAdd = useCallback((lat: number, lng: number) => {
    setPendingPin({ lat, lng })
    setPriceInput('')
    setTimeout(() => priceInputRef.current?.focus(), 80)
  }, [])

  const handleScreenshotPinSave = useCallback(() => {
    if (!pendingPin) return
    const price = priceInput.trim()
    if (!PRICE_RE.test(price)) return
    setScreenshotPins(prev => [...prev, {
      id: `sp_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
      lat: pendingPin.lat,
      lng: pendingPin.lng,
      price,
    }])
    setPendingPin(null)
    setPriceInput('')
  }, [pendingPin, priceInput])

  const handleScreenshotPinDelete = useCallback((id: string) => {
    setScreenshotPins(prev => prev.filter(p => p.id !== id))
  }, [])

  const handleClearAllPins = useCallback(() => {
    setScreenshotPins([])
    try { localStorage.removeItem('screenshotPins') } catch {}
  }, [])

  // ── Prefetch on first hover (desktop) or touchstart (mobile) ────
  // On mobile: touchstart fires ~100-200ms before the click event,
  // giving Next.js time to start fetching the page before navigation.
  const prefetchScooter = useCallback((id: string) => {
    if (prefetched.current.has(id)) return
    prefetched.current.add(id)
    router.prefetch(`/scooter/${id}`)
  }, [router])

  const filtered = useMemo(() => {
    let list = initialScooters.filter(s => {
      if (shopIdFilter && s.shopId !== shopIdFilter) return false
      if (filters.category !== 'all' && s.category !== filters.category) return false
      if (s.pricePerDay > filters.priceMax) return false
      if (filters.deliveryNow && !s.deliveryAvailable) return false
      if (filters.helmetIncluded && !s.helmetIncluded) return false
      if (filters.location !== 'all') {
        const isExact = (s.shop?.locationVisibility ?? 'exact') === 'exact' && (s.shop?.hasPrecisePin ?? false)
        const zone = isExact
          ? getNearestZone(s.lat, s.lng)
          : (getZoneForLocation(s.location) ?? getZoneForLocation(s.shop?.location ?? '') ?? getNearestZone(s.lat, s.lng))
        if (!zone || zone.key !== filters.location.replace(/-/g, ' ')) return false
      }
      if (filters.depositProtected && !s.shop?.depositProtectedMember) return false
      if (filters.noPassport && s.depositType === 'passport') return false
      if (filters.requiredFeatures.length > 0 && !filters.requiredFeatures.every(f => s.features.includes(f))) return false
      if (filters.requiredAccessories.length > 0 && !filters.requiredAccessories.every(a => s.features.includes(a))) return false
      if (filters.depositTypeFilter) {
        const dt = s.depositType
        if (filters.depositTypeFilter === 'cash'     && dt !== 'cash'     && dt !== 'both') return false
        if (filters.depositTypeFilter === 'passport' && dt !== 'passport' && dt !== 'both') return false
        if (filters.depositTypeFilter === 'both'     && dt !== 'both') return false
      }
      // Map bounds filter (when "Search this area" is clicked)
      if (mapBounds) {
        const { lat, lng } = { lat: s.lat, lng: s.lng }
        if (lng < mapBounds.sw[0] || lng > mapBounds.ne[0]) return false
        if (lat < mapBounds.sw[1] || lat > mapBounds.ne[1]) return false
      }
      if (fuseMatchIds && !fuseMatchIds.has(s.id)) return false
      return true
    })

    if (filters.sortBy === 'recommended') {
      // "Default view" = no search/filters/manual sort touched at all — the
      // truly-unfiltered landing state. Randomize that one case so the same
      // high-scoring listings don't always appear first; any active filter,
      // search, or non-default sort still uses the existing score-based sort.
      const isDefaultView =
        filters.category === 'all' &&
        !filters.deliveryNow &&
        !filters.helmetIncluded &&
        filters.location === 'all' &&
        !filters.depositProtected &&
        !filters.noPassport &&
        filters.requiredFeatures.length === 0 &&
        filters.requiredAccessories.length === 0 &&
        !filters.depositTypeFilter &&
        filters.priceMin === DEFAULT_FILTERS.priceMin &&
        filters.priceMax === maxPrice &&
        fuseMatchIds === null &&
        !shopIdFilter &&
        !mapBounds

      list = isDefaultView ? shuffleUnpinned(list, randomSeed) : sortByRecommended(list)
    }
    if (filters.sortBy === 'price_asc')  list = [...list].sort((a, b) => a.pricePerDay - b.pricePerDay)
    if (filters.sortBy === 'price_desc') list = [...list].sort((a, b) => b.pricePerDay - a.pricePerDay)
    if (filters.sortBy === 'rating')     list = [...list].sort((a, b) => b.rating - a.rating)
    if (filters.sortBy === 'distance' && userLocation) {
      list = [...list].sort((a, b) =>
        haversineKm(userLocation.lat, userLocation.lng, a.lat, a.lng) -
        haversineKm(userLocation.lat, userLocation.lng, b.lat, b.lng)
      )
    }
    return list
  }, [filters, fuseMatchIds, initialScooters, mapBounds, shopIdFilter, userLocation, maxPrice, randomSeed])

  // Keep ref in sync after render so handleSelectFromMap always sees the latest filtered list
  useEffect(() => { filteredRef.current = filtered }, [filtered])

  // Track empty search results — fires when a real search/filter yields nothing
  useEffect(() => {
    if (filtered.length === 0 && (debouncedSearch || filters.category !== 'all' || filters.location !== 'all')) {
      trackEvent({ eventType: 'empty_search', metadata: { search: debouncedSearch, category: filters.category, location: filters.location } })
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [filtered.length === 0, debouncedSearch, filters.category, filters.location])


  return (
    <div className="min-h-screen bg-white pt-16">
      {/* ── Sticky top bar ── */}
      <div className="sticky top-16 z-30 bg-white border-b border-[#e8e8e4]">
        <div className="max-w-6xl mx-auto px-4 py-2">
          {/* Search row — includes mobile List/Map toggle */}
          <div className="flex items-center gap-2 mb-2">
            <div className="relative flex-1">
              <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-[#9c9c98] pointer-events-none" />
              <input
                type="text"
                placeholder="Search scooters, brands, locations…"
                value={search}
                onChange={e => setSearch(e.target.value)}
                className="w-full pl-11 pr-4 py-2.5 bg-[#f8f8f6] border border-[#e8e8e4] rounded-full text-sm placeholder:text-[#9c9c98] focus:outline-none focus:border-[#FF6B35] focus:bg-white transition-colors"
              />
            </div>

            {/* Near me — icon-only on mobile, icon+label on sm+ */}
            <button
              onClick={handleNearMe}
              disabled={geoLoading}
              className={cn(
                'flex-shrink-0 flex items-center gap-1.5 px-3 py-2 rounded-full border text-sm font-medium transition-colors',
                userLocation
                  ? 'bg-[#2563eb] text-white border-[#2563eb]'
                  : 'bg-white text-[#5c5c58] border-[#e8e8e4] hover:border-[#d0d0cc]',
                geoLoading && 'opacity-60 cursor-wait',
              )}
            >
              {geoLoading
                ? <Loader2 className="w-3.5 h-3.5 animate-spin flex-shrink-0" />
                : <Navigation className="w-3.5 h-3.5 flex-shrink-0" />
              }
              <span className="hidden sm:inline whitespace-nowrap">
                {geoLoading ? 'Locating…' : 'Near me'}
              </span>
            </button>

            {/* Desktop map toggle — pill, stays in sticky bar */}
            <button
              onClick={toggleMap}
              className={cn(
                'hidden lg:flex items-center gap-1.5 px-4 py-2 rounded-full border text-sm font-medium flex-shrink-0 transition-colors',
                showMap
                  ? 'bg-[#0f0f0e] text-white border-[#0f0f0e]'
                  : 'bg-white text-[#5c5c58] border-[#e8e8e4] hover:border-[#d0d0cc]'
              )}
            >
              <Map className="w-3.5 h-3.5" />
              {showMap ? 'Hide map' : 'Show map'}
            </button>

            {/* Mobile toggle — inside sticky bar, always accessible */}
            <div className="flex lg:hidden items-center gap-0.5 bg-[#f0f0ec] rounded-full p-1 flex-shrink-0">
              <button
                onClick={() => setMobileView('list')}
                className={cn(
                  'flex items-center gap-1 px-3 py-1.5 rounded-full text-xs font-semibold transition-all',
                  mobileView === 'list'
                    ? 'bg-white text-[#0f0f0e] shadow-sm'
                    : 'text-[#9c9c98] hover:text-[#5c5c58]'
                )}
              >
                <List className="w-3 h-3" />
                List
              </button>
              <button
                onClick={() => {
                  setMobileView('map')
                  setFilters(prev => ({ ...prev, location: 'all' }))
                  setSelectedId(null)
                  setShopIdFilter(null)
                }}
                className={cn(
                  'flex items-center gap-1 px-3 py-1.5 rounded-full text-xs font-semibold transition-all',
                  mobileView === 'map'
                    ? 'bg-[#0f0f0e] text-white shadow-sm'
                    : 'text-[#9c9c98] hover:text-[#5c5c58]'
                )}
              >
                <Map className="w-3 h-3" />
                Map
              </button>
            </div>
          </div>

          <ExploreFilters filters={filters} onChange={setFilters} showRecommended={showRecommended} maxPrice={maxPrice} />
          {shopIdFilter && (() => {
            const shopName = initialScooters.find(s => s.shopId === shopIdFilter)?.shop?.name
            return shopName ? (
              <div className="flex items-center gap-1.5 mt-1.5">
                <div className="flex items-center gap-1.5 pl-3 pr-2 py-1 bg-[#FF6B35] text-white text-xs font-semibold rounded-full">
                  <span>{shopName}</span>
                  <button
                    onClick={() => setShopIdFilter(null)}
                    className="w-4 h-4 flex items-center justify-center rounded-full bg-white/20 hover:bg-white/30 transition-colors flex-shrink-0"
                  >
                    <span className="text-[9px] leading-none">✕</span>
                  </button>
                </div>
              </div>
            ) : null
          })()}
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-4 pt-4 pb-5">
        {/* ── DESKTOP LAYOUT ── */}
        <div className="hidden lg:flex gap-5">
          <div
            className="min-w-0 transition-all duration-300 ease-in-out"
            style={{ width: showMap ? '42%' : '100%' }}
          >
            {filtered.length === 0 ? <EmptyState /> : (
              <div className={`grid gap-3 ${showMap ? 'grid-cols-1 xl:grid-cols-2' : 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-4'}`}>
                {filtered.map(scooter => (
                  <div
                    key={scooter.id}
                    ref={setCardRef(scooter.id)}
                    onClick={() => setSelectedId(prev => prev === scooter.shopId ? null : scooter.shopId)}
                    onMouseEnter={() => {
                      if (scooter.shopId) handleHoverEnter(scooter.shopId)
                      prefetchScooter(scooter.id)
                    }}
                    onMouseLeave={handleHoverLeave}
                    onTouchStart={() => prefetchScooter(scooter.id)}
                    className={cn(
                      'transition-all duration-150',
                      selectedId === scooter.shopId ? 'ring-2 ring-[#FF6B35] rounded-[20px]' : '',
                      hoveredId === scooter.shopId && selectedId !== scooter.shopId ? 'ring-1 ring-[#FF6B35]/40 rounded-[20px]' : '',
                    )}
                  >
                    <ScooterCard scooter={scooter} compact />
                  </div>
                ))}
              </div>
            )}
          </div>

          {showMap && (
            <div className="flex-1 min-w-0">
              <div className="sticky top-36">
                <div className="relative">
                  <ScooterMap
                    scooters={filtered}
                    selectedId={selectedId ?? undefined}
                    hoveredId={hoveredId ?? undefined}
                    onSelect={handleSelectFromMap}
                    onHover={setHoveredId}
                    onBoundsChange={setMapBounds}
                    onZoneClick={handleZoneClick}
                    className="h-[calc(100vh-10rem)] min-h-[480px]"
                    showPopup={false}
                    debugMode={debugMode}
                    screenshotPins={isAdmin ? screenshotPins : undefined}
                    screenshotMode={isAdmin && screenshotMode}
                    onScreenshotPinAdd={isAdmin ? handleScreenshotPinAdd : undefined}
                    onScreenshotPinDelete={isAdmin ? handleScreenshotPinDelete : undefined}
                    userLocation={userLocation}
                  />
                  {(() => {
                    if (!selectedId) return null
                    const shopScooters = filtered.filter(s => s.shopId === selectedId)
                    if (shopScooters.length === 0) return null
                    const shop = shopScooters[0].shop
                    const thumbs = shopScooters
                      .slice(0, 3)
                      .map(s => s.coverImage ?? s.images[0])
                      .filter(Boolean) as string[]
                    return (
                      <div className="absolute bottom-4 right-4 z-20 bg-white rounded-[16px] shadow-[0_4px_24px_rgba(0,0,0,0.16)] p-3.5 w-[200px]">
                        <button
                          onClick={() => setSelectedId(null)}
                          className="absolute top-2.5 right-2.5 w-6 h-6 bg-[#f0f0ec] rounded-full flex items-center justify-center"
                        >
                          <span className="text-[10px] text-[#5c5c58] font-bold leading-none">✕</span>
                        </button>

                        <div className="flex items-center gap-2 mb-2.5 pr-6">
                          {shop?.logo && (
                            <img src={shop.logo} alt={shop.name} className="w-8 h-8 rounded-lg object-cover flex-shrink-0" />
                          )}
                          <div className="min-w-0">
                            <p className="text-[12px] font-bold text-[#0f0f0e] leading-tight truncate">{shop?.name ?? '—'}</p>
                            <p className="text-[10px] text-[#9c9c98]">{shopScooters.length} scooter{shopScooters.length !== 1 ? 's' : ''}</p>
                          </div>
                        </div>

                        {thumbs.length > 0 && (
                          <div className="flex gap-1.5 mb-2.5">
                            {thumbs.map((src, i) => (
                              <img key={i} src={src} alt="" className="w-[56px] h-[42px] rounded-[8px] object-cover flex-shrink-0" />
                            ))}
                          </div>
                        )}

                        <button
                          onClick={() => {
                            setShopIdFilter(selectedId)
                            setSelectedId(null)
                          }}
                          className="flex items-center justify-center w-full py-2 bg-[#FF6B35] text-white text-[11px] font-bold rounded-full hover:bg-[#e85d29] transition-colors"
                        >
                          View scooters
                        </button>
                      </div>
                    )
                  })()}
                </div>
              </div>
            </div>
          )}
        </div>

        {/* ── MOBILE LAYOUT ── */}
        <div className="lg:hidden">
          {mobileView === 'list' ? (
            filtered.length === 0 ? <EmptyState /> : (
              // xs 2-column: 4+ cards visible without scroll on iPhone
              <div className="grid grid-cols-2 gap-2.5">
                {filtered.map(scooter => (
                  <div
                    key={scooter.id}
                    onTouchStart={() => prefetchScooter(scooter.id)}
                    onClick={() => setSelectedId(prev => prev === scooter.shopId ? null : scooter.shopId)}
                  >
                    <ScooterCard scooter={scooter} xs />
                  </div>
                ))}
              </div>
            )
          ) : (
            <div className="relative">
              <ScooterMap
                scooters={filtered}
                selectedId={selectedId ?? undefined}
                hoveredId={hoveredId ?? undefined}
                onSelect={(id) => { setSelectedId(id) }}
                onHover={setHoveredId}
                onZoneClick={handleZoneClick}
                activeZone={filters.location === 'all' ? null : filters.location}
                className="h-[calc(100svh-13rem)] min-h-[420px]"
                showPopup={false}
                debugMode={debugMode}
                screenshotPins={isAdmin ? screenshotPins : undefined}
                screenshotMode={isAdmin && screenshotMode}
                onScreenshotPinAdd={isAdmin ? handleScreenshotPinAdd : undefined}
                onScreenshotPinDelete={isAdmin ? handleScreenshotPinDelete : undefined}
                userLocation={userLocation}
              />
              {(() => {
                if (!selectedId) return null
                const shopScooters = filtered.filter(s => s.shopId === selectedId)
                if (shopScooters.length === 0) return null
                const shop = shopScooters[0].shop
                const thumbs = shopScooters
                  .slice(0, 3)
                  .map(s => s.coverImage ?? s.images[0])
                  .filter(Boolean) as string[]
                return (
                  <div className="absolute bottom-24 right-4 z-20 bg-white rounded-[16px] shadow-[0_4px_24px_rgba(0,0,0,0.16)] p-3.5 w-[200px]">
                    <button
                      onClick={() => setSelectedId(null)}
                      className="absolute top-2.5 right-2.5 w-6 h-6 bg-[#f0f0ec] rounded-full flex items-center justify-center"
                    >
                      <span className="text-[10px] text-[#5c5c58] font-bold leading-none">✕</span>
                    </button>

                    <div className="flex items-center gap-2 mb-2.5 pr-6">
                      {shop?.logo && (
                        <img src={shop.logo} alt={shop.name} className="w-8 h-8 rounded-lg object-cover flex-shrink-0" />
                      )}
                      <div className="min-w-0">
                        <p className="text-[12px] font-bold text-[#0f0f0e] leading-tight truncate">{shop?.name ?? '—'}</p>
                        <p className="text-[10px] text-[#9c9c98]">{shopScooters.length} scooter{shopScooters.length !== 1 ? 's' : ''}</p>
                      </div>
                    </div>

                    {thumbs.length > 0 && (
                      <div className="flex gap-1.5 mb-2.5">
                        {thumbs.map((src, i) => (
                          <img key={i} src={src} alt="" className="w-[56px] h-[42px] rounded-[8px] object-cover flex-shrink-0" />
                        ))}
                      </div>
                    )}

                    {selectedId && (
                      <button
                        onClick={() => {
                          setShopIdFilter(selectedId)
                          setMobileView('list')
                          setSelectedId(null)
                        }}
                        className="flex items-center justify-center w-full py-2 bg-[#FF6B35] text-white text-[11px] font-bold rounded-full"
                      >
                        View scooters
                      </button>
                    )}
                  </div>
                )
              })()}
            </div>
          )}
        </div>
      </div>

      {process.env.NODE_ENV === 'development' && <ImageMetricsOverlay />}

      {/* ── Admin: Screenshot Pins panel ── */}
      {!profileLoading && isAdmin && adminPanelVisible && (
        <div className="fixed bottom-24 right-4 z-[9000] bg-[#0f0f0e] text-white rounded-[16px] p-3.5 shadow-2xl w-[148px] select-none">
          <p className="text-[9px] font-bold uppercase tracking-[0.12em] text-[#9c9c98] mb-2.5">
            Admin · Explore
          </p>

          {/* Recommended sort toggle */}
          <div className="flex items-center justify-between mb-3">
            <span className="text-[9px] text-[#9c9c98] leading-tight">Recommended</span>
            <button
              onClick={() => toggleRecommended(!showRecommended)}
              className={[
                'rounded-full transition-colors duration-200 shrink-0',
                showRecommended ? 'bg-[#FF6B35]' : 'bg-white/20',
              ].join(' ')}
              style={{ width: 30, height: 18, position: 'relative' }}
            >
              <span
                className="absolute top-[2px] bg-white rounded-full transition-all duration-200"
                style={{ width: 14, height: 14, left: showRecommended ? 14 : 2 }}
              />
            </button>
          </div>

          <p className="text-[9px] text-[#9c9c98] mb-1.5">Screenshot Pins</p>
          <div className="flex gap-1.5 mb-2">
            <button
              onClick={() => setScreenshotMode(false)}
              className={cn(
                'flex-1 text-xs font-semibold py-1.5 rounded-[9px] transition-colors',
                !screenshotMode
                  ? 'bg-[#FF6B35] text-white'
                  : 'bg-white/[0.08] text-white/60 hover:bg-white/[0.15] hover:text-white',
              )}
            >
              Off
            </button>
            <button
              onClick={() => setScreenshotMode(true)}
              className={cn(
                'flex-1 text-xs font-semibold py-1.5 rounded-[9px] transition-colors',
                screenshotMode
                  ? 'bg-[#FF6B35] text-white'
                  : 'bg-white/[0.08] text-white/60 hover:bg-white/[0.15] hover:text-white',
              )}
            >
              On
            </button>
          </div>
          {screenshotMode && (
            <p className="text-[9px] text-[#9c9c98] mb-2 leading-tight">Click map to add a pin</p>
          )}
          {screenshotPins.length > 0 && (
            <button
              onClick={handleClearAllPins}
              className="w-full text-[9px] text-red-400 hover:text-red-300 transition-colors py-1"
            >
              Clear all ({screenshotPins.length})
            </button>
          )}
        </div>
      )}

      {/* ── Admin: price input modal (appears after map click in screenshot mode) ── */}
      {pendingPin && (
        <div className="fixed inset-0 z-[10000] flex items-center justify-center">
          <div
            className="absolute inset-0 bg-black/30"
            onClick={() => setPendingPin(null)}
          />
          <div className="relative bg-white rounded-[20px] shadow-2xl p-5 w-64">
            <p className="text-[11px] font-bold uppercase tracking-[0.1em] text-[#9c9c98] mb-3">Add Pin</p>
            <label className="block text-sm font-semibold text-[#0f0f0e] mb-1.5">Price (฿/day)</label>
            <input
              ref={priceInputRef}
              type="text"
              inputMode="text"
              value={priceInput}
              onChange={e => setPriceInput(e.target.value)}
              onKeyDown={e => {
                if (e.key === 'Enter') handleScreenshotPinSave()
                if (e.key === 'Escape') setPendingPin(null)
              }}
              placeholder="300"
              className="w-full px-3 py-2.5 border border-[#e8e8e4] rounded-[10px] text-sm font-semibold focus:outline-none focus:border-[#FF6B35] mb-3 [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
            />
            <div className="flex gap-2">
              <button
                onClick={() => setPendingPin(null)}
                className="flex-1 py-2.5 text-sm font-semibold text-[#5c5c58] bg-[#f8f8f6] rounded-full hover:bg-[#f0f0ec] transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={handleScreenshotPinSave}
                disabled={!PRICE_RE.test(priceInput.trim())}
                className="flex-1 py-2.5 text-sm font-semibold text-white bg-[#FF6B35] rounded-full hover:bg-[#e85d29] disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
              >
                Save
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

function EmptyState() {
  return (
    <div className="text-center py-20">
      <div className="w-14 h-14 bg-[#f8f8f6] rounded-[18px] flex items-center justify-center mx-auto mb-4">
        <Bike className="w-7 h-7 text-[#9c9c98]" strokeWidth={1.5} />
      </div>
      <h3 className="text-lg font-bold text-[#0f0f0e] mb-2">No scooters found</h3>
      <p className="text-[#5c5c58] text-sm">Try adjusting your filters or search terms.</p>
    </div>
  )
}
